### ISSUE TITLE
Getbhavcopy-Eq-Ind.py giving error

### ISSUE THREAD

**Issue by FinAstro** [pparesh25/Getbhavcopy-alternative#13]
The system throws error when I execute python Getbhavcopy-Eq-Ind.py..

**Comment by nukulyadav** [comment]
@FinAstro New file was created by @pparesh25  but for index I think code needs to be merged to get a single bhavcopy output.

Right now it's downloading without index data in it. @pparesh25 - If you can adjust the code please to provide a single bhavcopy with stocks and index data inside.

**Comment by FinAstro** [comment]
> @FinAstro New file was created by @pparesh25 but for index I think code needs to be merged to get a single bhavcopy output.
> 
> Right now it's downloading without index data in it. @pparesh25 - If you can adjust the code please to provide a single bhavcopy with stocks and index data inside.

As of day before yesterday, when I tried last, it is not downloading any NSE Eq data after 5th July..

**Comment by pparesh25** [comment]
If you are using this file "Getbhavcopy-Eq-Ind.py" to download data then I will add the new version of it but in redmi file I have explained better how to use this "Getbhavcopy-Eq-with original Indexes name .py" file and what is its benefit and I have already created the new version of that file "New-Getbhavcopy-Eq-with original Indexes name .py".  and you can use it.

**Comment by FinAstro** [comment]
Thanks Paresh for your message.. It seems, the file name needs to be changed to remove the spaces else python gives error.. It solved my issues. at least now i can download the files. Regards

**Comment by FinAstro** [comment]
Can i close this issue now?

**Comment by pparesh25** [comment]
New-Getbhavcopy-Eq-Ind.py file is added use this and tell me if any issue remain.
