### ISSUE TITLE
F&O Volume Data

### ISSUE THREAD

**Issue by rajendraghelani** [pparesh25/Getbhavcopy-alternative#17]
Dear Sir,

Python based utility to download F&O data works perfectly fine. I just want to ask and suggest you that, in NSE Bhavcopy uploaded by NSE contains both data viz. Volume (No of Shares Traded) and No of Contracts Traded. In the Utility, It downloads, No of Contracts. NSE Periodically changes Market lot size of Futures and Options Contracts. In this case, Volume indicator gives false sign. It will be easier if we change it to Volume column instead of No of Contracts column.

Is it possible to edit or customize Python file at our end? or can you upload it. If so, please, guide. 

One more thing, In NSE Indices Data are with original names. can we change it to Symbols to match historical data saved in my Old Data Directory?

Thanks & Regards,

**Comment by pparesh25** [comment]
Thanks I will look into this and let you know here after making the changes.

**Comment by pparesh25** [comment]
[new_bhavcopy_format_readme.xlsx](https://github.com/user-attachments/files/16482236/new_bhavcopy_format_readme.xlsx)
[BhavCopy_NSE_FO_0_0_0_20240709_F_0000.csv.zip](https://github.com/user-attachments/files/16482239/BhavCopy_NSE_FO_0_0_0_20240709_F_0000.csv.zip)
[fo05JUL2024bhav.csv.zip](https://github.com/user-attachments/files/16482251/fo05JUL2024bhav.csv.zip)

NSE provides Total Traded Contracts and Total Traded Value columns in 'Fo Bhavcopy' prior to 6 July 2024 and also in changed format 'Fo Bhavcopy' thereafter.  Total traded shares do not have a separate column in the 'Fo Bhavcopy'. Here you can see the old and new format sample attached and NSE attached file detailing the old and changed column names. lot size column was not given in  'Fo Bhavcopy' before 8 July 2024, but now it is added in new format so it is possible to calculate total number of traded share in changed format after 8 July 2024 but not possible in 'Fo Bhavcopy' before 8 July 2024

**Comment by rajendraghelani** [comment]
Thanks for the reply. I checked all the files attached by you. In the utility, file is taken from F&O-UDiFF Common Bhavcopy Final (zip) But I checked the file available under head F&O - Bhavcopy (Fo.zip) which contains two separate bhav copies of futures and options. Screen shot from NSE website attached. can we find any feasible solution to arrive at total volume instead of total contracts? 
![NSE](https://github.com/user-attachments/assets/d84fef2a-7697-42cd-a3e7-8c5ffb4ee83b)

**Comment by pparesh25** [comment]
The NSE consistently provides this file under the same name, "fo.zip." Unfortunately, downloading the file based on its date is not feasible because the date is not included in the file name. Consequently, it is not possible to generate a URL based on the file name.

**Comment by rajendraghelani** [comment]
Dear Paresh,

 

Thanks for the reply and efforts for checking available options. Now, I do understand that it’s not possible to generate a URL based on file name. it’s not technically feasible. 

 

Best Regards,
