### ISSUE TITLE
Error in downloading

### ISSUE THREAD

**Issue by AJEY1964** [pparesh25/Getbhavcopy-alternative#18]
Getting the messege as in the image
<img width="862" alt="Screenshot 2024-08-25 223114" src="https://github.com/user-attachments/assets/1a89d9d7-06ce-42f3-a4ca-2005cc8ffab7">
Also is there any way to download files before 2016 ?

Thank you.

**Comment by pparesh25** [comment]
modified all code to better error handling please download it and remove all bhavcopy from "C:\Getbhavcopy_NSE" for manually enter date.

**Comment by AJEY1964** [comment]
I am still getting the same error
