### ISSUE TITLE
Issue in Downloading from 27th October 2023

### ISSUE THREAD

**Issue by vantive** [pparesh25/Getbhavcopy-alternative#4]
Hi,

Looks like there's an issue perhaps due to some changes at the NSE archives presumably could have started from Oct 2023.
Not sure if I am the one facing this issue? or does it have to do something with my usage of this tool on my PC.
but till 15th Sept I was able to download it properly and import in AB.

I am getting files in csv format after the below errors. But the csv file is thowing many errors during AB import.

Can anyone look into this or provide a workaround if there's already a solution available?

thanks in advance

Here is the errors that I am getting.

Logs:

D:\Getbhavcopy-alternative-main>py Getbhavcopy-Eq-Ind.py
Enter the start date (YYYY-MM-DD): 2023-10-26
Enter the end date (YYYY-MM-DD): 2023-10-26
Eq-bhavcopy cm26OCT2023bhav.csv.zip downloaded.
File '2023-01-02-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-01-03-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-01-04-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-01-05-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-01-06-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-01-09-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-01-10-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-01-11-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-01-12-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-01-13-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-01-16-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-01-17-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-01-18-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-01-19-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-01-20-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-01-23-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-01-24-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-01-25-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-01-27-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-01-30-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-01-31-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-02-01-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-02-02-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-02-03-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-02-06-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-02-07-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-02-08-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-02-09-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-02-10-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-02-13-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-02-14-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-02-15-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-02-16-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-02-17-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-02-20-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-02-21-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-02-22-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-02-23-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-02-24-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-02-27-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-02-28-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-03-01-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-03-02-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-03-03-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-03-06-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-03-08-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-03-09-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-03-10-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-03-13-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-03-14-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-03-15-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-03-16-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-03-17-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-03-20-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-03-21-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-03-22-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-03-23-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-03-24-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-03-27-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-03-28-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-03-29-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-03-31-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-04-03-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-04-05-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-04-06-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-04-10-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-04-11-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-04-12-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-04-13-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-04-17-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-04-18-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-04-19-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-04-20-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-04-21-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-04-24-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-04-25-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-04-26-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-04-27-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-04-28-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-05-02-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-05-03-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-05-04-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-05-05-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-05-08-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-05-09-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-05-10-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-05-11-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-05-12-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-05-15-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-05-16-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-05-17-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-05-18-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-05-19-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-05-22-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-05-23-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-05-24-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-05-25-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-05-26-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-05-29-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-05-30-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-05-31-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-06-01-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-06-02-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-06-05-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-06-06-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-06-07-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-06-08-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-06-09-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-06-12-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-06-13-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-06-14-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-06-15-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-06-16-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-06-19-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-06-20-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-06-21-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-06-22-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-06-23-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-06-26-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-06-27-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-06-28-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-06-30-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-07-03-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-07-04-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-07-05-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-07-06-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-07-07-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-07-10-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-07-11-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-07-12-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-07-13-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-07-14-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-07-17-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-07-18-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-07-19-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-07-20-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-07-21-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-07-24-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-07-25-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-07-26-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-07-27-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-07-28-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-07-31-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-08-01-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-08-02-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-08-03-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-08-04-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-08-07-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-08-08-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-08-09-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-08-10-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-08-11-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-08-14-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-08-16-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-08-17-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-08-18-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-08-21-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-08-22-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-08-23-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-08-24-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-08-25-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-08-28-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-08-29-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-08-30-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-08-31-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-09-01-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-09-04-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-09-05-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-09-06-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-09-07-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-09-08-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-09-11-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-09-12-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-09-13-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-09-14-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-09-15-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-09-18-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-09-20-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-09-21-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-09-22-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-09-25-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-09-26-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-09-27-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-09-28-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-09-29-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-10-03-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-10-04-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-10-05-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-10-06-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-10-09-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-10-10-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-10-11-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-10-12-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-10-13-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-10-16-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-10-17-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-10-18-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-10-19-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-10-20-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
File '2023-10-23-NSE-EQ.csv' does not end with 'bhav.csv' and was not renamed.
Traceback (most recent call last):
  File "D:\Getbhavcopy-alternative-main\Getbhavcopy-Eq-Ind.py", line 161, in <module>
    modify_files(output_folder)
  File "D:\Getbhavcopy-alternative-main\Getbhavcopy-Eq-Ind.py", line 135, in modify_files
    df = df.drop(columns=columns_to_remove)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\frame.py", line 5258, in drop
    return super().drop(
           ^^^^^^^^^^^^^
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\generic.py", line 4549, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\generic.py", line 4591, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\indexes\base.py", line 6699, in drop
    raise KeyError(f"{list(labels[mask])} not found in axis")
KeyError: "['LAST', 'PREVCLOSE', 'TOTTRDVAL', 'TOTALTRADES', 'ISIN'] not found in axis"

**Comment by madhanji** [comment]
this software working now?
sw auther pls comment/reply sir

**Comment by pparesh25** [comment]
![image](https://github.com/pparesh25/Getbhavcopy-alternative/assets/11598930/31e39ae5-9cca-46f5-abd6-48139b20037d)
