### ISSUE TITLE
Unable to download for 20Jan2024

### ISSUE THREAD

**Issue by 123allanapps123** [pparesh25/Getbhavcopy-alternative#6]
Hi Paresh. Could you please help me with the bavcopy file for the 20th of Jan2024 . Software is not able to download it
Thanks

**Comment by ghkumarchd** [comment]
This application is Not downloading any data when 
NSE working on Saturday  or sunday any solution?

**Comment by pparesh25** [comment]
Added Weekend_Getbhavcopy-Eq-with original Indexes name.py file to download data in weekend.  But my recommendation is to use this to download data only on weekends when the market is open.
