### ISSUE TITLE
Date Format in extracted data not compatible with amibroker

### ISSUE THREAD

**Issue by kdmenghani13** [pparesh25/Getbhavcopy-alternative#7]
Hi @pparesh25, I am able to run the code and download the bhavcopy in txt file. However, file has the date format as "20240429" So when I try to import it in amibroker tool it fails with an error. As a workaround I have to modify the date to "2024-04-29" to make it work.
How can we set the correct date format in the files?
And offcourse, awesome work!! kudos!

**Comment by pparesh25** [comment]
Format is fine, It's import issue, change your ahcii import parameter and try again. Search internet for how to first time import amibroker data and save and use that format.
