### ISSUE TITLE
csv not available to save index data

### ISSUE THREAD

**Issue by nukulyadav** [pparesh25/Getbhavcopy-alternative#8]
Nice work, but now after CSV format discontinuation from NSE, not been able to download the EOD Data.

**Comment by AryaB-ai** [comment]
Issue has come up since 8th of July, 2024.

**Comment by nukulyadav** [comment]
> Issue has come up since 8th of July, 2024.

Yes @AryaB-ai @pparesh25 . NSE has stopped CSV format now. Therefore this issue.

**Comment by niravshah74** [comment]
Shall we get improved app? As NSE has stopped few format based data but data is still there

**Comment by nukulyadav** [comment]
Yes @niravshah74 , there is no alternative besides that.

**Comment by pparesh25** [comment]
I haven't downloaded the data for two or three days, before that everything was fine, so today I will check and then give an update.

**Comment by nukulyadav** [comment]
Ok @pparesh25 . Yes, Kindly check and fix. Indeed NSE stopped providing CSV format bhavcopies recently.

**Comment by nukulyadav** [comment]
@pparesh25 Any updates?

**Comment by pparesh25** [comment]
A new file has been added with name "New-Getbhavcopy-Eq-with original Indexes name " use it to download data after 8 july 2024.

**Comment by AryaB-ai** [comment]
Thanks.
NSE EOD FO file also has the same issue.
