### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by jaajvel** [pparesh25/Getbhavcopy-alternative#9]
The NSE has changed the algorithm for downloads one week back, hence the programme is not currently working

**Comment by pparesh25** [comment]
I haven't downloaded the data for two or three days, before that everything was fine, so today I will check and then give an update.

**Comment by jaajvel** [comment]
Thank you Sir

**Comment by pparesh25** [comment]
A new file has been added with name "New-Getbhavcopy-Eq-with original Indexes name " use it to download data after 8 july 2024.
